name: "Sync Figma Variables from FigMayo"
description: "Fetches figma variables from FigMayo API and creates a PR to update them in your repo."
author: "FigMayo"
branding:
  icon: "zap"
  color: "blue"
keywords:
  - figmayo
  - figma
  - design-tokens
  - variables
  - github-action
  - design-system
  - token-sync
  - automation
  - figma-integration
  - pull-request
  - design-ops
inputs:
  figmayo-api-key:
    description: "FigMayo API Key"
    required: true
  file-path:
    description: "Path to save the figma variables JSON file"
    required: true
outputs:
  pr-url:
    description: "URL of the created pull request"

runs:
  using: "composite"
  steps:
    - name: Checkout Base Branch
      uses: actions/checkout@v4

    - name: Create or Switch to Update Branch
      if: env.changes == 'true'
      shell: bash
      run: |
        # Checkout the base branch
        git fetch origin ${{ github.ref_name }}
        git checkout ${{ github.ref_name }}

        # Create or switch to 'update-figma-variables[figmayo]'
        git checkout -B update-figma-variables[figmayo]

    - name: Ensure Target Directory Exists
      shell: bash
      run: |
        dir=$(dirname "${{ inputs.file-path }}")
        mkdir -p "$dir" # Create the directory if it doesn't exist

    - name: Fetch Figma Variables
      shell: bash
      run: |
        curl -H "x-figmayo-key: ${{ inputs.figmayo-api-key }}" https://app.figmayo.com/api/v2/plugin/variables -o ${{ inputs.file-path }}

    - name: Stage File for Git Diff
      shell: bash
      run: |
        git add ${{ inputs.file-path }}

    - name: Check for Changes
      id: git-check
      shell: bash
      run: |
        if git diff --cached --quiet; then
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "changes=true" >> $GITHUB_ENV
        fi

        # Debugging Output
        echo "Changes detected: ${{ env.changes }}"

    - name: Commit Changes
      if: env.changes == 'true'
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ inputs.file-path }}
        git commit -m "chore: update Figma variables from FigMayo API"
        git push origin update-figma-variables

    - name: Create Pull Request
      if: env.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        base: ${{ github.ref_name }} # PR into the branch that triggered the workflow
        branch: update-figma-variables[figmayo] # Source branch for the PR
        title: "chore: update Figma variables"
        body: "This PR updates Figma variables from the FigMayo API."
        labels: "figmayo"
